**Numpy is a package for scientific computing with python**

We are going to run some functions in numpy which I wrote them below :

**Array Creation**

arange, array, copy, empty, empty_like, eye, fromfile, fromfunction, identity, linspace, logspace, mgrid, ogrid, ones, ones_like, r, zeros, zeros_like

**Conversions**

ndarray.astype, atleast_1d, atleast_2d, atleast_3d, mat

**Manipulations**

array_split, column_stack, concatenate, diagonal, dsplit, dstack, hsplit, hstack, ndarray.item, newaxis, ravel, repeat, reshape, resize, squeeze, swapaxes, take, transpose, vsplit, vstack

**Questions**

all, any, nonzero, where


**Ordering**

argmax, argmin, argsort, max, min, ptp, searchsorted, sort


**Operations**

choose, compress, cumprod, cumsum, inner, ndarray.fill, imag, prod, put, putmask, real, sum
Basic Statistics
cov, mean, std, var

In [1]:
import numpy as np

a = np.array([1,2])
b = np.array([2,1])
print(a*b)
print(sum(a*b))

[2 2]
4


This is the dot product of a and b with numpy :

In [10]:
a = np.array([1,2])
b = np.array([2,1])
# we can also write a.dot(b) or b.dot(a)
print(np.dot(a,b))

4


In [14]:
a=np.array([1,2])
print(np.sqrt((a*a).sum()))
print(a**2)
print(np.log(a))
print(np.exp(a))
print(np.sin(a))

2.23606797749979
[1 4]
[0.         0.69314718]
[2.71828183 7.3890561 ]
[0.84147098 0.90929743]


In [46]:
a = np.array([1,2])
b = np.array([2,1])

cosangle = (np.dot(a,b) / (np.linalg.norm(a)* np.linalg.norm(b)))
print(cosangle)

#np.sin(x) , np.cos(x)  , np.tan(x)
# np.arctan(x) , np.arcsin(x)

angle = np.arccos(cosangle)
print(angle)

0.7999999999999998
0.6435011087932847


np.linalg.norm?

In [27]:
# pay attention to ()
Z = np.zeros((10,10))
# also we can make a 10 by 10 matrix with elments by value 1 or 0
#O = np.ones((10,10))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [32]:
#R = np.random.random((10,10))
R= np.random.randn(10,10)
print(R)
#gives the mean
print("The mean is equal to : "+ str(R.mean()))
# gives the variance
print("The variance is equal to : "+ str(R.var()))

[[-7.56161357e-01  5.46144407e-03  6.83288708e-01  9.40349316e-01
   1.28910833e+00 -1.36447604e+00  6.83341528e-01 -5.94975874e-02
   5.54921992e-01 -7.21167155e-01]
 [ 1.83485839e-01 -5.56245434e-01 -6.42320637e-01 -2.38099159e-01
   1.33318519e+00  6.60966655e-01 -1.42963947e+00  4.94973228e-02
  -7.86782108e-02  9.84229894e-01]
 [ 1.71062338e-01  1.48099490e+00  2.23703935e-02 -3.22541550e-01
   3.17961839e-01 -1.04127740e+00  1.12987849e+00 -1.02063214e+00
   6.03011283e-01 -4.96592187e-01]
 [ 4.57148761e-01  1.16596905e+00  1.97136388e+00 -6.66019274e-01
  -8.62689705e-01  1.71277733e-01  1.51426395e+00 -6.57220729e-01
  -3.16331186e-01 -1.21427733e+00]
 [-6.15937733e-01  9.39156704e-01 -3.13169244e-01 -1.74979517e+00
   2.15881922e-01  1.28048919e+00 -8.00099798e-01 -1.42892853e-02
   8.00582757e-01  5.51314898e-01]
 [ 3.40374937e-01  8.38047367e-01 -3.14880914e-01 -1.14372556e+00
   1.74537287e+00 -1.54054928e-02  3.79629500e-01 -3.96310009e-01
   1.48912380e+00 -3.98504481e-01

In [40]:
a = np.arange(6).reshape(2, 3)
print(a)
print(a.shape)

[[0 1 2]
 [3 4 5]]
(2, 3)


In [44]:
print(a.dtype)
print(a.dtype.name)

int32
int32


In [4]:
import numpy as np
a=np.arange(10.0,30,5)
#the size in bytes of each element of the array.
print(a.itemsize)
#dimention
print(a.ndim)
a

8
1


array([10., 15., 20., 25.])

In [8]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
print(c)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [8]:
from numpy import pi
# x= np.linspace( 0, 2, 9 )  # 9 numbers from 0 to 2
y = np.linspace( 0, 2*pi, 100 ) 
print(y)

[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.39465405 5.45812057 5.52158709 5.58505361 5.648520

To force NumPy to print the entire array, you can change the printing options using set_printoptions.

In [13]:
np.set_printoptions(threshold=np.nan)
#y = np.linspace( 0, 2*pi, 100000 ) 
#y

In [14]:
A = np.array( [[1,1],
               [0,1]] )
B = np.array( [[2,0],
               [3,4]] )
# elementwise product
print(A*B)
sum(A*B)

[[2 0]
 [0 4]]


array([2, 4])

In [19]:
#matrix product
print(A@B)
#print(A.dot(B))

[[5 4]
 [3 4]]


In [21]:
print(A.max())
print(B.min())

1
0


In [24]:
#sum of each column
B.sum(axis=0) 

array([5, 4])

In [25]:
# min of each row
B.min(axis=1) 

array([0, 3])

In [27]:
#  cumulative sum along each row
B.cumsum(axis=1)   

array([[2, 2],
       [3, 7]], dtype=int32)

In [28]:
# returns the array, flattened
B.ravel()

array([2, 0, 3, 4])

In [29]:
#transpose
B.T

array([[2, 3],
       [0, 4]])

In [18]:
# C works with rows
C = A.reshape(4,1)
#pointer
C[2,0] = 999
print(A)


[[  1   1]
 [999   1]]


In [37]:
A.resize((1,4))
print(A)

[[1 1 0 1]]


In [39]:
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))
#vertical
np.vstack((a,b))

array([[1., 2.],
       [4., 7.],
       [1., 3.],
       [2., 8.]])

In [40]:
#horizontal
np.hstack((a,b))

array([[1., 2., 1., 3.],
       [4., 7., 2., 8.]])

In [19]:
a = np.array([4.,2.])
b = np.array([3.,8.])
print(np.hstack((a,b)))
np.column_stack((b,a))

[4. 2. 3. 8.]


array([[3., 4.],
       [8., 2.]])

In [54]:
from numpy import newaxis
a = np.array([1, 2 ,3 ])
a[:,newaxis]

array([[1],
       [2],
       [3]])

In [55]:
np.concatenate((a, b), axis=0)

array([1., 2., 3., 3., 8.])

In [62]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a , b), axis= 1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [63]:
np.concatenate((a , b.T), axis= 1)

array([[1, 2, 5],
       [3, 4, 6]])

In [20]:
a = np.floor(10*np.random.random((2,12)))
print(a)
np.hsplit(a,3)   # Split a into 3

[[1. 8. 5. 5. 4. 5. 3. 5. 5. 7. 0. 6.]
 [3. 3. 0. 0. 1. 9. 7. 5. 8. 0. 7. 3.]]


[array([[1., 8., 5., 5.],
        [3., 3., 0., 0.]]), array([[4., 5., 3., 5.],
        [1., 9., 7., 5.]]), array([[5., 7., 0., 6.],
        [8., 0., 7., 3.]])]

In [65]:
np.hsplit(a,(3,4))   # Split a after the third and the fourth column

[array([[1., 1., 9.],
        [0., 6., 9.]]), array([[9.],
        [9.]]), array([[6., 1., 0., 2., 8., 8., 3., 1.],
        [0., 5., 8., 5., 1., 9., 8., 7.]])]

In [71]:
b = a
c = a.view()  # c is a view of the data owned by a
b is a

True

In [72]:
c is a

False

In [73]:
c.base is a 

True

In [82]:
print(a.shape)
b.shape = (6,4)
print(a.shape)


(2, 12)
(6, 4)


In [83]:
c.shape = (3,8)
print(a.shape)

(6, 4)


In [84]:
#deep copy
d = a.copy()                          # a new array object with new data is created
d is a

False

In [5]:
import numpy as np
#linear algebra

a= np.array([[1,2,3] ,
           [5,6,7],
            [8,9,10]])
#inverse
np.linalg.inv(a)

array([[-1.0293942e+16,  2.4019198e+16, -1.3725256e+16],
       [ 2.0587884e+16, -4.8038396e+16,  2.7450512e+16],
       [-1.0293942e+16,  2.4019198e+16, -1.3725256e+16]])

In [6]:
I= np.eye(2)
np.trace(I)

2.0

In [8]:
y = np.array([[4],[3],[2]])
# find the x in ax=y
np.linalg.solve(a, y)

array([[ 3.431314e+15],
       [-6.862628e+15],
       [ 3.431314e+15]])

In [9]:
# Parameters: square matrix
# Returns: The eigenvalues, each repeated according to its multiplicity.
            #The normalized (unit "length") eigenvectors, such that the
            #column ``v[:,i]`` is the eigenvector corresponding to the
            #eigenvalue ``w[i]`` .
np.linalg.eig(a)

(array([ 1.81566040e+01, -1.15660396e+00, -8.44149895e-16]),
 array([[ 0.20565406,  0.80862166,  0.40824829],
        [ 0.55048922,  0.01041684, -0.81649658],
        [ 0.80911559, -0.58823678,  0.40824829]]))

In [10]:
#outer product
np.outer(a, y)

array([[ 4,  3,  2],
       [ 8,  6,  4],
       [12,  9,  6],
       [20, 15, 10],
       [24, 18, 12],
       [28, 21, 14],
       [32, 24, 16],
       [36, 27, 18],
       [40, 30, 20]])

In [11]:
from numpy.linalg import matrix_power
matrix_power(a,2)

array([[ 35,  41,  47],
       [ 91, 109, 127],
       [133, 160, 187]])

In [13]:
from numpy import linalg as LA
LA.eigvals(a)

array([ 1.81566040e+01, -1.15660396e+00, -8.44149895e-16])

In [14]:
LA.norm(a)

19.209372712298546

In [15]:
LA.det(a)

2.914335439641041e-16

In [16]:
# Return matrix rank of array using SVD method
LA.matrix_rank(a)

2

In [1]:
y = np.linspace( 0, 2*pi, 100 ) 

11

In [2]:
np.matmul([[1,2],[3,4]] , [[1,1],[2,2]]) # matrix product

array([[ 5,  5],
       [11, 11]])

In [3]:
a = np.random.randn(9, 6)
#SVD
u, s, vh = np.linalg.svd(a, full_matrices=True)
u

array([[ 0.08905285, -0.15833944, -0.30818729, -0.08629067,  0.81909802,
        -0.01308369, -0.33931149,  0.16523832,  0.22592916],
       [ 0.32276471, -0.26605693, -0.33411698,  0.17408144, -0.23050229,
        -0.52224398,  0.30990205,  0.08818962,  0.50339982],
       [ 0.43417083, -0.52313443,  0.61226755,  0.14386865,  0.0823357 ,
         0.3327054 ,  0.0596214 ,  0.02653554,  0.14326696],
       [-0.06948655, -0.35237487, -0.00489203, -0.19432806, -0.27548426,
        -0.16892143, -0.31258602,  0.72950653, -0.31448437],
       [ 0.71119382,  0.46626049, -0.08027939,  0.1565229 ,  0.10651636,
        -0.01156481,  0.11787288,  0.25112961, -0.39676282],
       [-0.16614346,  0.05362041,  0.38200326,  0.59377136,  0.16880454,
        -0.5779632 , -0.27948985, -0.08470446, -0.15233003],
       [-0.10262577, -0.03489189,  0.31954853, -0.4969056 ,  0.34372363,
        -0.40377793,  0.56697416,  0.04194795, -0.18660706],
       [-0.35947211,  0.25632722,  0.09747262,  0.36915192,  0

In [4]:
s

array([4.67685406, 4.17982198, 3.40958171, 2.31014712, 1.38548175,
       0.65743182])

In [5]:
vh

array([[-0.42227855,  0.05935028,  0.38535295,  0.81262798,  0.09628645,
        -0.0051141 ],
       [-0.2431104 ,  0.43909592,  0.013192  , -0.25589801,  0.75187484,
        -0.34222581],
       [-0.67213458, -0.01436932,  0.14260228, -0.35829832, -0.50579658,
        -0.37879461],
       [-0.48997093, -0.37131781, -0.0518568 , -0.23345535,  0.29459156,
         0.69143102],
       [ 0.26534307, -0.27818851,  0.8731054 , -0.27063088,  0.12281369,
        -0.039584  ],
       [ 0.01829796,  0.76694203,  0.25688809, -0.13428259, -0.26022215,
         0.50963343]])

In [28]:
# sqrt(x1**2 + x2**2)
#A= 2*np.ones((3, 3))
#B = 6*np.ones((3, 3))
#print(A, B)
np.hypot(2*np.ones((3, 3)), 6*np.ones((3, 3)))  # sqr (40) = 6.32
#np.hypot(2*np.ones((3, 3)), [6]) #same answer

array([[6.32455532, 6.32455532, 6.32455532],
       [6.32455532, 6.32455532, 6.32455532],
       [6.32455532, 6.32455532, 6.32455532]])

In [7]:
rad = np.arange(12.)*np.pi/6
np.degrees(rad)

array([  0.,  30.,  60.,  90., 120., 150., 180., 210., 240., 270., 300.,
       330.])

In [8]:
deg = np.arange(12.) * 30.
np.radians(deg)

array([0.        , 0.52359878, 1.04719755, 1.57079633, 2.0943951 ,
       2.61799388, 3.14159265, 3.66519143, 4.1887902 , 4.71238898,
       5.23598776, 5.75958653])

In [9]:
np.deg2rad(180)

3.141592653589793

In [10]:
np.rad2deg(np.pi/2)

90.0

In [11]:
#Rounding functions 
np.around([0.5 , 0.2 , 0.7])

array([0., 0., 1.])

In [12]:
a = np.array([-2.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
np.rint(a)

array([-3., -2., -0.,  0.,  2.,  2.,  2.])

In [13]:
np.fix([2.1, 2.9, -2.1, -2.9])

array([ 2.,  2., -2., -2.])

In [14]:
np.floor(a)

array([-3., -2., -1.,  0.,  1.,  1.,  2.])

In [15]:
np.ceil(a)

array([-2., -1., -0.,  1.,  2.,  2.,  2.])

In [16]:
np.trunc(a)

array([-2., -1., -0.,  0.,  1.,  1.,  2.])

In [29]:
# subtract of each two pair
print(a)
np.diff(a)

[[1. 8. 5. 5. 4. 5. 3. 5. 5. 7. 0. 6.]
 [3. 3. 0. 0. 1. 9. 7. 5. 8. 0. 7. 3.]]


array([[ 7., -3.,  0., -1.,  1., -2.,  2.,  0.,  2., -7.,  6.],
       [ 0., -3.,  0.,  1.,  8., -2., -2.,  3., -8.,  7., -4.]])

In [18]:
#[-2.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0]
np.cumsum(a)

array([-2.7, -4.2, -4.4, -4.2, -2.7, -1. ,  1. ])

In [19]:
# return index of array from smallest 
np.argsort(a)

array([0, 1, 2, 3, 4, 5, 6], dtype=int64)

In [20]:
b = [4 , 2 , 8 , 5 , 12 ,0 , 26]
#equivalent np.sort
np.msort(b)

array([ 0,  2,  4,  5,  8, 12, 26])

In [21]:
np.sort_complex(b)

array([ 0.+0.j,  2.+0.j,  4.+0.j,  5.+0.j,  8.+0.j, 12.+0.j, 26.+0.j])

In [22]:
# np.argpartition
c = [26, 5 ,7 ,3 ,2 ,6]
np.partition(c, (1))

array([ 2,  3,  7,  5, 26,  6])

In [23]:
# np.argpartition
np.partition(c, (1,3))

array([ 2,  3,  5,  6, 26,  7])

In [24]:
a = [[2 , 4 , 1] ,
     [ 5  ,6 ,7]]
np.median(a, axis=0)

array([3.5, 5. , 4. ])

In [25]:
np.median(a, axis=1)

array([2., 6.])

In [35]:
a = [[2 , 4 , 1] ,   [ 5  ,6 ,7]]
np.median(a, axis=None, overwrite_input=True)
#print(a)

4.5

In [39]:
#np.mean(a)
np.average(a)

4.166666666666667

In [34]:
d = np. array([[10.,2 ,  4.],
               [ 3.,  2.,  1.]])
d[0,1] = np.nan
print(d)
print(np.median(d))

#np.nanmean
#np.nanstd
#np.nanvar
print(np.nanmedian(d))

[[10. nan  4.]
 [ 3.  2.  1.]]
nan
3.0


In [29]:
# standard_deviation 
np.std(a)

2.1147629234082532

In [30]:
# variance 
np.var(a)

4.472222222222222

In [31]:
np.cov(a)

array([[ 2.33333333, -0.5       ],
       [-0.5       ,  1.        ]])

In [32]:
np.correlate([1, 2, 3], [0, 1, 0.5])

array([3.5])

In [33]:
np.histogram(np.arange(4), bins=np.arange(5), density=True)

(array([0.25, 0.25, 0.25, 0.25]), array([0, 1, 2, 3, 4]))

In [35]:
np.all([True, False])

False

In [36]:
np.all([False, False])

False

In [37]:
np.any([True, False])

True

In [40]:
np.any([False, False])

False

In [39]:
#masking ( fancy indexing)
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a>3

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [41]:
a[a>3]

array([4, 5, 6, 7, 8, 9])

In [41]:
# Indices of elements that are non-zero. returns a tuple
#?
np.nonzero(a > 3)

TypeError: '>' not supported between instances of 'list' and 'int'

In [42]:
np.nonzero?

In [42]:
np.where(a < 5, a, 10*a)

array([[ 1,  2,  3],
       [ 4, 50, 60],
       [70, 80, 90]])

In [1]:
print("Thanks for reading")

Thanks for reading


src : https://www.numpy.org/